#!/usr/bin/env bash
if [ -f cmake_install.cmake ] ; then
	rm cmake_install.cmake
fi

if [ -f CMakeCache.txt ] ; then
	rm CMakeCache.txt
fi

if [ -f CMakeFiles ] ; then
	rm -rf CMakeFiles
fi

if [ -f Makefile ] ; then
	rm Makefile
fi

cmake .
make
#./blob-track
